#!/bin/sh
# Author: MarkusWessjohann
# Date: 02.11.2016
# Desc: creates a task from a redmine-Ticket-File

USAGE="addred issue-ID"

if [ $1 = usage ]; then
	cat <<EOF
    $USAGE  - Add Redmine-issue as task.

EOF
exit
fi

[ $# -lt 1 ] && die "usage: $TODO_SH $USAGE"
shift
ID=$1
[ "$ID" -eq "$ID" ] 2>/dev/null || die "usage: $TODO_SH $USAGE"

redmineConfig=`cygpath -w "$HOME/.redmine.conf.gpg"`

cd "/cygdrive/c/Program Files (x86)/GnuPG/bin/"
user_pass=`command "gpg.exe" -vvvvv -d "$redmineConfig" | \
  grep -v "Codepage" | \
  tr -d "$ ;"`
user=` echo "$user_pass" | \
  grep user | \
  cut -f2 -d"=" | \
  tr -d '"'`
password=` echo "$user_pass" | \
  grep pass | \
  cut -f2 -d"=" | \
  tr -d '"'`

if [ -z "$user_pass" ]
then
	echo "Couldn't decrypt File"
	exit 1
fi

curl  -H "Content-Type: application/xml" -u "$user:$password" -X GET "http://redmine.ao-intranet/issues/${ID}.xml" > /tmp/$ID.xml

thema=`xmllint.exe --xpath "string(//subject)" /tmp/$ID.xml`
projekt=`xmllint.exe --xpath "string(//project/@name)" /tmp/$ID.xml | tr " " "_"`
status=`xmllint.exe --xpath "string(//status/@name)" /tmp/$ID.xml`
zugewiesen=`xmllint.exe --xpath "string(//assigned_tp/@name)" /tmp/$ID.xml`
prio="(A)"

if [ "x$thema" == "x" ]
then
  echo "Redmine-issue not found: ${ID}";
  exit 1
fi
$TODO_FULL_SH list | grep "#$ID" 2>&1 >/dev/null
if [ "$?" -eq 0 ]
then
  echo "Redmine-issue already as Task (#$ID"
  exit 1
fi
todo="$prio #$ID - $thema +$projekt @Redmine"
$TODO_FULL_SH add "$todo"





